require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "Gemfile"
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - jobs/*
    - Rakefile
    - config.ru
    - .irbrc
  NewCops: enable

  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
