AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "config/**/*"
    - "Gemfile"
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - jobs/*
    - Rakefile
    - config.ru
  NewCops: enable

  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*