 steps:
 - name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp', 'gs://master_keys/line-message-yamanotenki/master.key', './config/']
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/line-message-yamanotenki:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/line-message-yamanotenki:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'line-message-yamanotenki'
   - '--image'
   - 'gcr.io/$PROJECT_ID/line-message-yamanotenki:$COMMIT_SHA'
   - '--region'
   - 'asia-northeast1'
   - '--set-env-vars'
   - 'RAILS_ENV=production,RAILS_LOG_TO_STDOUT=1'
   - '--allow-unauthenticated'

 images:
 - 'gcr.io/$PROJECT_ID/line-message-yamanotenki:$COMMIT_SHA'
