name: Eager Load

on:
  pull_request:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml
      - 'gcp/**'
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml
      - 'gcp/**'

jobs:
  eager-load:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RAILS_ENV: development
      EAGER_LOAD: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: run rspec
        run: bundle exec rails s -d
